export default {
'Ahhh':       {mp:  1, description: 'Soft plushy and very pleasant'},
'Antidote':   {mp:  2, description: 'Cures one monster of poison'},
'AquaCut':    {mp:  3, description: 'Inflicts severe damage on the water family'},
'AquaWall':   {mp:  5, description: 'Creates a barrier that blocks an attack'},
'Bang':       {mp:  5, description: 'Small explosions strike enemies [all]'},
'Barrier':    {mp:  3, description: 'Reduces damage from breath attacks [all]'},
'BazooCall':  {mp: 20, description: 'Summons Bazoo to battle'},
'BeastCut':   {mp:  3, description: 'Inflicts severe damage on the beast family'},
'Beat':       {mp:  4, description: 'Instantly slays an enemy'},
'BeDragon':   {mp:  9, description: 'Transforms the user into a ferocious'},
'Berserker':  {mp:  1, description: 'A powerful attack that leaves the user vulnerable'},
'BiAttack':   {mp:  3, description: 'A physical attack that strikes twice in succession'},
'BigBang':    {mp: 30, description: 'Creates an enormous explosion [all]'},
'BigTrip':    {mp:  3, description: 'Sweeps the legs out from under all enemies'},
'BirdBlow':   {mp:  3, description: 'Inflicts severe damage on the bird family'},
'BladeD':     {mp:  3, description: 'Protects the user and enables retaliation'},
'Blaze':      {mp:  2, description: 'Attacks an enemy with a fireball'},
'BlazeAir':   {mp:  4, description: 'Inflicts damage with a blast of fire [all]'},
'BlazeMore':  {mp:  4, description: 'Attacks an enemy with a large fireball'},
'BlazeMost':  {mp: 10, description: 'A towering pillar of fire roasts an enemy'},
'Blizzard':   {mp: 12, description: 'A wicked blizzard howls through enemies [all]'},
'Bolt':       {mp:  5, description: 'Lightning strikes enemies [all]'},
'BoltSlash':  {mp:  3, description: 'A sword attack made stronger by lightning'},
'Boom':       {mp:  8, description: 'A succession of explosions strikes enemies [all]'},
'Bounce':     {mp:  4, description: 'Bounces back all enemy spells'},
'BugBlow':    {mp:  3, description: 'Inflicts severe damage on the bug family'},
'CallHelp':   {mp:  4, description: 'Summons friends who attack in droves'},
'Chance':     {mp: 20, description: 'There is no telling what may happen'},
'ChargeUp':   {mp:  0, description: 'Inflicts severe damage on the next turn'},
'CleanCut':   {mp:  3, description: 'Inflicts severe damage on the material family'},
'Cover':      {mp:  2, description: 'Takes all attacks meant for another monster'},
'Curse':      {mp:  3, description: 'Lays a curse on all enemies'},
'CurseOff':   {mp:  2, description: 'Lifts a curs [all]'},
'DanceShut':  {mp:  6, description: 'Prevents all enemies from dancing'},
'DeChaoes':   {mp:  2, description: 'Clears confusion in all party monsters'},
'Defeat':     {mp:  7, description: 'Instantly slays enemies [all]'},
'Defense':    {mp:  4, description: 'Lowers DEF of all enemy monsters'},
'DeMagic':    {mp:  7, description: 'Lifts the effects of all spells on enemies [all]'},
'DevilCut':   {mp:  3, description: 'Inflicts severe damage on the devil family'},
'DiagoCall':  {mp: 20, description: 'Summons Diago to battle'},
'Dodge':      {mp:  4, description: 'Deflects any physical attack to another monster'},
'DrakSlash':  {mp:  3, description: 'Inflicts severe damage on the dragon family'},
'EagleEye':   {mp:  0, description: 'Determines the presence of items nearby'},
'EerieLite':  {mp:  2, description: 'Weakens all enemies to magic spells'},
'Errand':     {mp:  2, description: 'Makes the monster run an errand for 100G'},
'EvilSlash':  {mp:  3, description: 'A powerful but wildly aimed sword attack'},
'Explodet':   {mp: 15, description: 'Huge explosions blast enemies [all]'},
'Farewell':   {mp: -1, description: 'Revives dead mates in exchange for own life [all]'},
'FireAir':    {mp:  2, description: 'Inflicts damage with a breath of fire [all]'},
'Firebal':    {mp:  4, description: 'Attacks enemies with a blast of fire [all]'},
'Firebane':   {mp:  6, description: 'Attacks enemies with a wall of fire [all]'},
'Firebolt':   {mp: 10, description: 'A huge wall of fire incinerates enemies [all]'},
'FireSlash':  {mp:  3, description: 'A fiery sword attack'},
'Focus':      {mp:  0, description: 'Enables two moves in the next turn'},
'FrigidAir':  {mp:  2, description: 'Inflicts damage with a breath of ice [all]'},
'Geyser':     {mp:  2, description: 'Opens a geyser to send an enemy flying'},
'GigaSlash':  {mp: 20, description: 'The ultimate sword attack'},
'Guardian':   {mp:  4, description: 'Takes all attacks meant for party monsters'},
'Heal':       {mp:  2, description: 'Restores HP by 30 - 40'},
'HealAll':    {mp:  7, description: 'Fully restores HP'},
'HealMore':   {mp:  5, description: 'Restores HP by 75 - 90'},
'HealUs':     {mp: 18, description: 'Restores HP by 90 - 120 [all]'},
'HealUsAll':  {mp: 36, description: 'Fully restores HP [all]'},
'HellBlast':  {mp: 25, description: 'Strikes all enemies with huge lightning'},
'HighJump':   {mp:  5, description: 'The user leaps and attacks in the next turn'},
'Hustle':     {mp: 12, description: 'A dance that restores HP by 70 - 80 [all]'},
'IceAir':     {mp:  4, description: 'Inflicts damage with a freezing breath [all]'},
'Icebolt':    {mp:  3, description: 'Small chunks of ice hail down on enemies [all]'},
'IceSlash':   {mp:  3, description: 'A sword attack made stronger by the power of ice'},
'IceStorm':   {mp:  8, description: 'Inflicts damage by exhaling a blizzard [all]'},
'Imitate':    {mp:  4, description: 'Imitates the enemy\'s moves'},
'Increase':   {mp:  3, description: 'Raises DEF of party monsters [all]'},
'Infermore':  {mp:  4, description: 'Twisters tear through enemies [all]'},
'Infermost':  {mp:  8, description: 'A huge tornado roars through enemies [all]'},
'Infernos':   {mp:  2, description: 'Razor sharp whirlwinds slash enemies [all]'},
'Informer':   {mp:  0, description: 'Use to obtain infformation on monsters'},
'Ironize':    {mp:  2, description: 'Changes all party monsters into chunks of iron'},
'K.O.Dance':  {mp:  6, description: 'A dance that induces death in all enemies'},
'Kamikaze':   {mp:  1, description: 'Leaves the user and target on the verge of death'},
'LegSweep':   {mp:  1, description: 'Sweeps the leg out from under one enemy'},
'LifeDance':  {mp: -1, description: 'A sacrificial dance to revive dead friends'},
'LifeSong':   {mp: 20, description: 'Revives all dead friends in the next turn'},
'Lightning':  {mp:  3, description: 'Summons a lightning storm [all]'},
'LoveRain':   {mp: 28, description: 'Summons rain that restores HP'},
'LureDance':  {mp:  2, description: 'A dance that makes all enemies want to join in'},
'Lushlicks':  {mp:  2, description: 'Licks one enemy to stop it from one turn'},
'MagicBack':  {mp:  4, description: 'Bounces back a spell once'},
'MagicWall':  {mp:  3, description: 'Raises protection against magic spells [all]'},
'MapMagic':   {mp:  2, description: 'Checks the surrounding area\'s terrain'},
'Massacre':   {mp:  3, description: 'Inflicts severe damage on one friend or foe'},
'Meditate':   {mp:  8, description: 'Meditates to restore HP by 500'},
'MegaMagic':  {mp: -1, description: 'The ultimate attack spell'},
'MetalCut':   {mp:  3, description: 'Inflicts damage on a high DEF enemy'},
'MouthShut':  {mp:  6, description: 'Prevents all enemies from using breath attacks'},
'MPass':      {mp: 20, description: 'Gives 15MP to a party monster'},
'MPassMore':  {mp: 40, description: 'Gives 30MP to a party monster'},
'MPassMost':  {mp:100, description: 'Gives 80MP to a party monster'},
'MultiCut':   {mp: 20, description: 'A crosscutting sword attack [all]'},
'NapAttack':  {mp:  2, description: 'A physical attack that may put the target to sleep'},
'NumbOff':    {mp:  2, description: 'Cures paralysis and sleep [all]'},
'OddDance':   {mp:  0, description: 'A dance that reduces an enemy\'s MP'},
'Outside':    {mp:  2, description: 'Instantly warps the party out from caves and towers'},
'PalsyAir':   {mp:  4, description: 'A breath that paralyzes all enemies'},
'PaniCall':   {mp:  5, description: 'Confuses all enemies'},
'PaniDance':  {mp:  4, description: 'A dance that confuses all enemies'},
'Paralyze':   {mp:  3, description: 'A physical attack that may paralyze the target'},
'Pheromone':  {mp:  0, description: 'Attracts enemy monsters of the opposite gender'},
'PoisonAir':  {mp:  4, description: 'A breath that badly poisons all enemies'},
'PoisonGas':  {mp:  3, description: 'A breath that poisons all enemies'},
'PoisonHit':  {mp:  2, description: 'A physical attack that may poison the target'},
'PsyceUp':    {mp:  3, description: 'Inflicts severe damage at the end of the turn'},
'QuadHits':   {mp:  6, description: 'A physical attack that strikes four times'},
'Radiant':    {mp:  2, description: 'A blast of light blinds all the enemies'},
'RainSlash':  {mp:  5, description: 'A sword attack that hits all enemies'},
'Ramming':    {mp:  1, description: 'A fullbody tackle that also hurts the user'},
'Revive':     {mp: 20, description: 'Revives a dead monster'},
'RobDance':   {mp:  0, description: 'A dance that steals an enemy\'s MP'},
'RobMagic':   {mp:  0, description: 'Steals MP from an enemy'},
'RockThrow':  {mp:  5, description: 'Hurls giant boulders at enemies [all]'},
'Sacrifice':  {mp:  1, description: 'The user explodes to inflict damage on all enemies'},
'SamsiCall':  {mp: 20, description: 'Summons Samsi to battle'},
'SandStorm':  {mp:  2, description: 'Obscures the visibility of all enemies'},
'Sap':        {mp:  3, description: 'Lowers DEF of one enemy'},
'Scorching':  {mp:  8, description: 'Inflicts damage with a huge blast of fire [all]'},
'SealPray':   {mp: 15, description: 'Seals a skill used by the enemy'},
'Shears':     {mp:  3, description: 'Inflicts severe damage on the plant family'},
'SickLick':   {mp:  4, description: 'Licks one enemy to reduce its DEF'},
'SideStep':   {mp:  1, description: 'A quickfooted skill for dodging attacks'},
'Sleep':      {mp:  3, description: 'Makes a single enemy sleep'},
'SleepAir':   {mp:  3, description: 'A breath that induces sleep in all enemies'},
'SleepAll':   {mp:  5, description: 'Makes all enemies sleep'},
'SlimeBlow':  {mp:  3, description: 'Inflicts severe damage on the slime family'},
'Slow':       {mp:  3, description: 'Lowers AGL of one enemy'},
'SlowAll':    {mp:  4, description: 'Lowers AGL of all enemy monsters'},
'SnowStorm':  {mp:  5, description: 'Enemies are flash frozen [all]'},
'Speed':      {mp:  2, description: 'Raises AGL of one monster'},
'SpeedUp':    {mp:  3, description: 'Raises AGL of party monsters [all]'},
'SquallHit':  {mp:  2, description: 'A physical attack that hits first'},
'StepGuard':  {mp:  2, description: 'Protects the party from injurious terrain'},
'StopSpell':  {mp:  3, description: 'Prevents spell casting by all enemies'},
'StormWind':  {mp: 10, description: 'Bounces back all breath attacks to all enemies'},
'StrongD':    {mp:  3, description: 'Strongly protects the user against all attacks'},
'SuckAir':    {mp:  0, description: 'Holds in a breath to inflict severe damage next turn'},
'SuckAll':    {mp:  2, description: 'Inhales all breath attacks meant for the party'},
'Surge':      {mp:  7, description: 'Eliminates all status problems among friends'},
'Surround':   {mp:  3, description: 'Surrounds all enemies in a mirage'},
'TailWind':   {mp:  6, description: 'Bounces back a breath attack to an enemy'},
'TakeMagic':  {mp:  2, description: 'Absorbs the MP of a spell cast against the user'},
'TatsuCall':  {mp: 20, description: 'Summons Tatsu to battle'},
'ThickFog':   {mp:  8, description: 'Creates a fog that prevents the use of all spells'},
'Thordain':   {mp: 15, description: 'Huge shards of lightning rip enemies [all]'},
'TidalWave':  {mp: 15, description: 'Summons a towering wall of water [all]'},
'Transform':  {mp:  5, description: 'Transforms the user into a chosen enemy'},
'TwinHits':   {mp:  6, description: 'Doubles the ATK of one monster'},
'TwinSlash':  {mp:  2, description: 'Inflicts severe damage but also hurts the user'},
'UltraDown':  {mp:  7, description: 'Greatly weakens an enemy'},
'Upper':      {mp:  2, description: 'Raises DEF of one monster'},
'VacuSlash':  {mp:  3, description: 'A sword attack enhanced by whirlwinds'},
'Vaccuum':    {mp:  6, description: 'Creates a tornado with vicious winds [all]'},
'Vivify':     {mp: 10, description: 'May revive a dead monster'},
'WarCry':     {mp:  3, description: 'A terrifying cry that stops all enemies'},
'WaterShot':  {mp:  5, description: 'Shoots a high volume of water at an enemy'},
'Whistle':    {mp:  0, description: 'Attracts enemy monsters'},
'WhiteAir':   {mp: 16, description: 'Looses a white shining breath of ice [all]'},
'WhiteFire':  {mp: 16, description: 'Inflicts damage with incredible fire [all]'},
'WindBeast':  {mp:  3, description: 'Slashes a single monster with sharp whirlwinds'},
'YellHelp':   {mp:  8, description: 'Summons a mass of friends that attack in droves'},
'Zap':        {mp: 10, description: 'Power bolts of lightning lash enemies [all]'},
'ZombieCut':  {mp:  3, description: 'Inflicts severe damage on the zombie family'},
}
